name: Save in repo
on:
  push:
    branches:
      - main
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository central
        uses: actions/checkout@v3
        with:
          repository: 'Rodcarm/controller'
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: get files in txt
        run: |
          contenido=$(tr '\n' ' ' < files/new-files/archivesToTest.txt)
          echo "contenido=$contenido" >> $GITHUB_ENV
      - name: Get files in central repository
        uses: actions/checkout@v3
        with:
          repository: 'Rodcarm/personal-website'
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: 'main'
      - name: Show repo info for personal website
        run: |
          cd main
          echo "Current repository: $(basename $(git remote get-url origin))"
      - name: Push file to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: ${{ env.contenido }}
          destination-branch: 'main'
          destination-username: 'Rodcarm'
          destination-repository: 'gitActionspersonal-website'
          commit-email: rcarmona@realmetrics.io