name: Clone files
on:
  push:
    branches:
      - main
    paths:
      - 'files/new-files/*'
jobs:
  clone-file:
    runs-on: ubuntu-latest
    steps:
      - name: Get personal-website
        uses: actions/checkout@v4
        with:
          repository: 'Rodcarm/controller'
          token: ${{ secrets.API_TOKEN_GITHUB }}
          fetch-depth: 0
      - name: get file changes
        run: |
          fileconf=$(git diff --name-only ${{github.event.before}} ${{github.event.after}})
          echo "fileconf=${fileconf}" >> $GITHUB_ENV
      - name: clone personal-website
        run: |
          paths=$(jq -r ".paths[]" ${{env.fileconf}})
          echo "paths list ${paths}"
          projects=$(jq -r ".projects[]" ${{env.fileconf}})
          echo "projects list ${projects}"
          commit=$(jq -r ".commit_message" ${{env.fileconf}})
          CLONE_DIRECTORY=$(mktemp -d)
          git config --global user.name "Rodrigo"
          git config --global user.email "rcarmona@realmetrics.io"
          rm -rf .git
          git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/Rodcarm/personal-website.git repo
          cd repo
          ls -la
          for project in "${projects[@]}"
          do
            rm -rf "$CLONE_DIRECTORY"/*
            echo "Project process ${project}"
    
            echo "clone repo project"
            git clone --single-branch --branch "main" "https://${{ secrets.API_TOKEN_GITHUB }}@github.com/Rodcarm/$project.git" "$CLONE_DIRECTORY"

            echo "CLONE DIRECTORY"
            ls -la "$CLONE_DIRECTORY"

            for path in "${paths}"
            do
              DESTINATION_DIRECTORY=$(dirname "$path")/
              echo "directory ${DESTINATION_DIRECTORY}"
              echo "path ${path}"
              mkdir -p "$CLONE_DIRECTORY/$DESTINATION_DIRECTORY"
              cp -rvf "./$path" "$CLONE_DIRECTORY/$DESTINATION_DIRECTORY"
            done
            cd "$CLONE_DIRECTORY"

            echo "Commit and push"
            ORIGIN_COMMIT="https://github.com/Rodcarm/controller/commit/$GITHUB_SHA"
            COMMIT_MESSAGE="${commit}"

            echo "git add"
            git add .
            git status

            git diff-index --quiet HEAD || git commit --message "$COMMIT_MESSAGE"
            echo "push commit"
            git push origin --set-upstream main

          done
 

